spring:
  data:
    mongodb:
      uri: mongodb+srv://root:root@cluster0.u6ivd.mongodb.net/events?retryWrites=true&w=majority
  jackson:
    serialization:
      write-dates-as-timestamps: false
  date-format: java.txt.SimpleDateFormat

server:
  error:
    include-stacktrace: never