server:
  port: 8091
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
jwt:
  secret: D9CEBEC7F8D5F695FCF72B8F71699AB5BB2850ADF304DB376654FF55AC312C901030EB61BD2533198173221F3C690DABF4925E0E180D7EF324DC7D06C8AED438
  jwtExpirationInMs: 18000000
spring:
  data:
    mongodb:
      uri: mongodb+srv://root:root@cluster0.u6ivd.mongodb.net/events?retryWrites=true&w=majority
  jackson:
    serialization:
      write-dates-as-timestamps: false
  date-format: java.txt.SimpleDateFormat
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/