server:
  port: 8091
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
jwt:
  secret: lucamusic
  jwtExpirationInMs: 18000000
spring:
  data:
    mongodb:
      uri: mongodb+srv://root:root@cluster0.u6ivd.mongodb.net/events?retryWrites=true&w=majority
  jackson:
    serialization:
      write-dates-as-timestamps: false
  date-format: java.txt.SimpleDateFormat
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/