server:
  port: 8093
  error:
    include-message: always
    include-binding-errors: always
    include-stack: never

spring:
  datasource:
    url: jdbc:mysql://sql11.freemysqlhosting.net:3306/sql11438881
    username: sql11438881
    password: ANqNpBNN6d
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format-sql: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/