server:
  port: 8092
  error:
    include-message: always
    include-binding-errors: always
    include-stack: never

spring:
  datasource:
    url: jdbc:mysql://sql11.freemysqlhosting.net:3306/sql11437168
    username: sql11437168
    password: GPBFf8F3vg
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format-sql: true